version: '3'

services:
  mongodb:
    container_name: portfolio_mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    logging:
            options:
                max-size: 1g
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongodata:/data/db
    networks:
      - portfolio-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  mongodata:
    external: true

networks:
  portfolio-network:
    external: true