name: Manual Build and Push Image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    uses: ./.github/workflows/jobs-build.yml
    with:
      config-path: .
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
